//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace AgenciaDeViaje
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ModeloDeDatosContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ModeloDeDatosContainer object using the connection string found in the 'ModeloDeDatosContainer' section of the application configuration file.
        /// </summary>
        public ModeloDeDatosContainer() : base("name=ModeloDeDatosContainer", "ModeloDeDatosContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ModeloDeDatosContainer object.
        /// </summary>
        public ModeloDeDatosContainer(string connectionString) : base(connectionString, "ModeloDeDatosContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ModeloDeDatosContainer object.
        /// </summary>
        public ModeloDeDatosContainer(EntityConnection connection) : base(connection, "ModeloDeDatosContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Clientes> ClientesSet
        {
            get
            {
                if ((_ClientesSet == null))
                {
                    _ClientesSet = base.CreateObjectSet<Clientes>("ClientesSet");
                }
                return _ClientesSet;
            }
        }
        private ObjectSet<Clientes> _ClientesSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Boletos> BoletosSet
        {
            get
            {
                if ((_BoletosSet == null))
                {
                    _BoletosSet = base.CreateObjectSet<Boletos>("BoletosSet");
                }
                return _BoletosSet;
            }
        }
        private ObjectSet<Boletos> _BoletosSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Vuelos> VuelosSet
        {
            get
            {
                if ((_VuelosSet == null))
                {
                    _VuelosSet = base.CreateObjectSet<Vuelos>("VuelosSet");
                }
                return _VuelosSet;
            }
        }
        private ObjectSet<Vuelos> _VuelosSet;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ClientesSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClientesSet(Clientes clientes)
        {
            base.AddObject("ClientesSet", clientes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BoletosSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBoletosSet(Boletos boletos)
        {
            base.AddObject("BoletosSet", boletos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VuelosSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVuelosSet(Vuelos vuelos)
        {
            base.AddObject("VuelosSet", vuelos);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModeloDeDatos", Name="Boletos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Boletos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Boletos object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Boletos CreateBoletos(global::System.Int32 id)
        {
            Boletos boletos = new Boletos();
            boletos.Id = id;
            return boletos;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModeloDeDatos", Name="Clientes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Clientes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Clientes object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Clientes CreateClientes(global::System.Int32 id)
        {
            Clientes clientes = new Clientes();
            clientes.Id = id;
            return clientes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModeloDeDatos", Name="Vuelos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vuelos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Vuelos object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Vuelos CreateVuelos(global::System.Int32 id)
        {
            Vuelos vuelos = new Vuelos();
            vuelos.Id = id;
            return vuelos;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion
    
    }

    #endregion
    
}
