//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("AgenciaViajeModel", "FK_dbo_Boletoes_dbo_Clientes_Cliente_Id", "Clientes", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ServicioWeb.Clientes), "Boletoes", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ServicioWeb.Boletoes))]

// Original file name:
// Generation date: 01/12/2012 11:31:17 p.m.
namespace ServicioWeb
{
    
    /// <summary>
    /// There are no comments for AgenciaViajeEntities in the schema.
    /// </summary>
    public partial class AgenciaViajeEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new AgenciaViajeEntities object using the connection string found in the 'AgenciaViajeEntities' section of the application configuration file.
        /// </summary>
        public AgenciaViajeEntities() : 
                base("name=AgenciaViajeEntities", "AgenciaViajeEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new AgenciaViajeEntities object.
        /// </summary>
        public AgenciaViajeEntities(string connectionString) : 
                base(connectionString, "AgenciaViajeEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new AgenciaViajeEntities object.
        /// </summary>
        public AgenciaViajeEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "AgenciaViajeEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Boletoes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Boletoes> Boletoes
        {
            get
            {
                if ((this._Boletoes == null))
                {
                    this._Boletoes = base.CreateQuery<Boletoes>("[Boletoes]");
                }
                return this._Boletoes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Boletoes> _Boletoes;
        /// <summary>
        /// There are no comments for Clientes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Clientes> Clientes
        {
            get
            {
                if ((this._Clientes == null))
                {
                    this._Clientes = base.CreateQuery<Clientes>("[Clientes]");
                }
                return this._Clientes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Clientes> _Clientes;
        /// <summary>
        /// There are no comments for Boletoes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToBoletoes(Boletoes boletoes)
        {
            base.AddObject("Boletoes", boletoes);
        }
        /// <summary>
        /// There are no comments for Clientes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToClientes(Clientes clientes)
        {
            base.AddObject("Clientes", clientes);
        }
    }
    /// <summary>
    /// There are no comments for AgenciaViajeModel.Boletoes in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AgenciaViajeModel", Name="Boletoes")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Boletoes : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Boletoes object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="tipo">Initial value of tipo.</param>
        /// <param name="refIdCliente">Initial value of RefIdCliente.</param>
        /// <param name="refIdVuelo">Initial value of RefIdVuelo.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Boletoes CreateBoletoes(int id, int tipo, int refIdCliente, int refIdVuelo)
        {
            Boletoes boletoes = new Boletoes();
            boletoes.Id = id;
            boletoes.tipo = tipo;
            boletoes.RefIdCliente = refIdCliente;
            boletoes.RefIdVuelo = refIdVuelo;
            return boletoes;
        }
        /// <summary>
        /// There are no comments for property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for property tipo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int tipo
        {
            get
            {
                return this._tipo;
            }
            set
            {
                this.OntipoChanging(value);
                this.ReportPropertyChanging("tipo");
                this._tipo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("tipo");
                this.OntipoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _tipo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OntipoChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OntipoChanged();
        /// <summary>
        /// There are no comments for property RefIdCliente in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int RefIdCliente
        {
            get
            {
                return this._RefIdCliente;
            }
            set
            {
                this.OnRefIdClienteChanging(value);
                this.ReportPropertyChanging("RefIdCliente");
                this._RefIdCliente = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("RefIdCliente");
                this.OnRefIdClienteChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _RefIdCliente;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnRefIdClienteChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnRefIdClienteChanged();
        /// <summary>
        /// There are no comments for property RefIdVuelo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int RefIdVuelo
        {
            get
            {
                return this._RefIdVuelo;
            }
            set
            {
                this.OnRefIdVueloChanging(value);
                this.ReportPropertyChanging("RefIdVuelo");
                this._RefIdVuelo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("RefIdVuelo");
                this.OnRefIdVueloChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _RefIdVuelo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnRefIdVueloChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnRefIdVueloChanged();
        /// <summary>
        /// There are no comments for property Vuelo_Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> Vuelo_Id
        {
            get
            {
                return this._Vuelo_Id;
            }
            set
            {
                this.OnVuelo_IdChanging(value);
                this.ReportPropertyChanging("Vuelo_Id");
                this._Vuelo_Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Vuelo_Id");
                this.OnVuelo_IdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _Vuelo_Id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnVuelo_IdChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnVuelo_IdChanged();
        /// <summary>
        /// There are no comments for Clientes in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("AgenciaViajeModel", "FK_dbo_Boletoes_dbo_Clientes_Cliente_Id", "Clientes")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Clientes Clientes
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Clientes>("AgenciaViajeModel.FK_dbo_Boletoes_dbo_Clientes_Cliente_Id", "Clientes").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Clientes>("AgenciaViajeModel.FK_dbo_Boletoes_dbo_Clientes_Cliente_Id", "Clientes").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Clientes in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Clientes> ClientesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Clientes>("AgenciaViajeModel.FK_dbo_Boletoes_dbo_Clientes_Cliente_Id", "Clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Clientes>("AgenciaViajeModel.FK_dbo_Boletoes_dbo_Clientes_Cliente_Id", "Clientes", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for AgenciaViajeModel.Clientes in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AgenciaViajeModel", Name="Clientes")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Clientes : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Clientes object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="nombre">Initial value of nombre.</param>
        /// <param name="apellido">Initial value of apellido.</param>
        /// <param name="telefono">Initial value of telefono.</param>
        /// <param name="fechaDeNacimiento">Initial value of fechaDeNacimiento.</param>
        /// <param name="correo">Initial value of correo.</param>
        /// <param name="password">Initial value of password.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Clientes CreateClientes(int id, string nombre, string apellido, string telefono, global::System.DateTime fechaDeNacimiento, string correo, string password)
        {
            Clientes clientes = new Clientes();
            clientes.Id = id;
            clientes.nombre = nombre;
            clientes.apellido = apellido;
            clientes.telefono = telefono;
            clientes.fechaDeNacimiento = fechaDeNacimiento;
            clientes.correo = correo;
            clientes.password = password;
            return clientes;
        }
        /// <summary>
        /// There are no comments for property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for property nombre in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string nombre
        {
            get
            {
                return this._nombre;
            }
            set
            {
                this.OnnombreChanging(value);
                this.ReportPropertyChanging("nombre");
                this._nombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("nombre");
                this.OnnombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _nombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnombreChanged();
        /// <summary>
        /// There are no comments for property apellido in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string apellido
        {
            get
            {
                return this._apellido;
            }
            set
            {
                this.OnapellidoChanging(value);
                this.ReportPropertyChanging("apellido");
                this._apellido = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("apellido");
                this.OnapellidoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _apellido;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnapellidoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnapellidoChanged();
        /// <summary>
        /// There are no comments for property telefono in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string telefono
        {
            get
            {
                return this._telefono;
            }
            set
            {
                this.OntelefonoChanging(value);
                this.ReportPropertyChanging("telefono");
                this._telefono = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("telefono");
                this.OntelefonoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _telefono;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OntelefonoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OntelefonoChanged();
        /// <summary>
        /// There are no comments for property fechaDeNacimiento in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime fechaDeNacimiento
        {
            get
            {
                return this._fechaDeNacimiento;
            }
            set
            {
                this.OnfechaDeNacimientoChanging(value);
                this.ReportPropertyChanging("fechaDeNacimiento");
                this._fechaDeNacimiento = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("fechaDeNacimiento");
                this.OnfechaDeNacimientoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _fechaDeNacimiento;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnfechaDeNacimientoChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnfechaDeNacimientoChanged();
        /// <summary>
        /// There are no comments for property correo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string correo
        {
            get
            {
                return this._correo;
            }
            set
            {
                this.OncorreoChanging(value);
                this.ReportPropertyChanging("correo");
                this._correo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("correo");
                this.OncorreoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _correo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncorreoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncorreoChanged();
        /// <summary>
        /// There are no comments for property password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string password
        {
            get
            {
                return this._password;
            }
            set
            {
                this.OnpasswordChanging(value);
                this.ReportPropertyChanging("password");
                this._password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("password");
                this.OnpasswordChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _password;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnpasswordChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnpasswordChanged();
        /// <summary>
        /// There are no comments for Boletoes in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("AgenciaViajeModel", "FK_dbo_Boletoes_dbo_Clientes_Cliente_Id", "Boletoes")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Boletoes> Boletoes
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Boletoes>("AgenciaViajeModel.FK_dbo_Boletoes_dbo_Clientes_Cliente_Id", "Boletoes");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Boletoes>("AgenciaViajeModel.FK_dbo_Boletoes_dbo_Clientes_Cliente_Id", "Boletoes", value);
                }
            }
        }
    }
}
